### ISSUE TITLE
3차 세미나 과제

### ISSUE THREAD

**Issue by timotheekim10** [DO-SOPT-iOS-Part/KimTaeGyeong-assignment#4]
# 💡이슈
3차 세미나 과제

# 📝 Todo
- 기본 구현과제
- [x] 지난번에 구현했던 내용들을, TableView와, CollectionView를 이용해서 구현

- 심화 구현과제
- [ ] 애플의 날씨앱은, 위로 스크롤 할때 헤더가 접히며 올라가게 되요. 해당부분을 날씨앱과 동일하게 구현
- [ ] 10일간의 일기예보에 있는 그라디언트 뷰를, 이미지를 사용하지 않고 구현
